
import {
    IconBolt,
    IconUsers,
    IconPackage,
    IconBuildingStore,
    IconStar,
} from "@/components/icon";

export const stats = [
    {
        icon: IconUsers,
        value: "50,000+",
        label: "ลูกค้าทั่วประเทศ",
        color: "from-sky-400 to-blue-500",
        bg: "bg-sky-50",
        border: "border-sky-100",
    },
    {
        icon: IconPackage,
        value: "5,000+",
        label: "รายการสินค้าในสต็อก",
        color: "from-violet-400 to-purple-500",
        bg: "bg-violet-50",
        border: "border-violet-100",
    },
    {
        icon: IconBuildingStore,
        value: "15+ ปี",
        label: "ประสบการณ์ในวงการ",
        color: "from-amber-400 to-orange-500",
        bg: "bg-amber-50",
        border: "border-amber-100",
    },
    {
        icon: IconStar,
        value: "4.9/5",
        label: "คะแนนความพึงพอใจ",
        color: "from-emerald-400 to-teal-500",
        bg: "bg-emerald-50",
        border: "border-emerald-100",
    },
    {
        icon: IconBolt,
        value: "24/7",
        label: "บริการซัพพอร์ต",
        color: "from-rose-400 to-pink-500",
        bg: "bg-rose-50",
        border: "border-rose-100",
    },
];


export const testimonials = [
    {
        id: 1,
        name: "คุณสมชาย วงศ์สุวรรณ",
        role: "ช่างไฟฟ้ามืออาชีพ",
        avatar: "สช",
        avatarColor: "from-sky-400 to-blue-500",
        rating: 5,
        text: "ใช้บริการ ElectroMax มา 5 ปีแล้ว สินค้าคุณภาพดีมาก ราคาสมเหตุสมผล และส่งเร็วมาก สั่งวันนี้ได้ของพรุ่งนี้เลย ทีมงานบริการดีเยี่ยม ให้ข้อมูลสินค้าละเอียด แนะนำให้ทุกคนลองใช้บริการเลยครับ",
        location: "กรุงเทพฯ",
        date: "2 สัปดาห์ที่แล้ว",
        verified: true,
    },
    {
        id: 2,
        name: "บริษัท พีดีเอ็ม คอนสตรัคชั่น",
        role: "ผู้รับเหมาก่อสร้าง",
        avatar: "PD",
        avatarColor: "from-violet-400 to-purple-500",
        rating: 5,
        text: "สั่งซื้อสินค้าจำนวนมากสำหรับโครงการก่อสร้าง ได้รับราคาพิเศษ บริการดีมาก มีทีมงานติดตามออเดอร์ตลอด สินค้าครบตามสั่ง ไม่มีของขาด ประทับใจมากครับ จะใช้บริการต่อแน่นอน",
        location: "สมุทรปราการ",
        date: "1 เดือนที่แล้ว",
        verified: true,
    },
    {
        id: 3,
        name: "คุณวรรณา ศรีสมบูรณ์",
        role: "เจ้าของบ้าน",
        avatar: "วร",
        avatarColor: "from-rose-400 to-pink-500",
        rating: 5,
        text: "ต้องการต่อไฟในบ้านใหม่ ไม่รู้จะเลือกซื้ออะไรดี ทีมงาน ElectroMax ให้คำแนะนำดีมาก แนะนำสินค้าที่เหมาะสม ราคาไม่แพง ของมาเร็ว คุณภาพดีกว่าที่คาดไว้มากเลยค่ะ",
        location: "เชียงใหม่",
        date: "3 สัปดาห์ที่แล้ว",
        verified: true,
    },
    {
        id: 4,
        name: "ร้านวัสดุก่อสร้าง เจริญชัย",
        role: "ร้านค้าส่ง",
        avatar: "จช",
        avatarColor: "from-amber-400 to-orange-500",
        rating: 5,
        text: "เราสั่งซื้อสินค้าจาก ElectroMax เพื่อมาจำหน่ายต่อในร้านเรา ราคาส่งดีมาก สินค้าหลากหลาย ครบครัน ส่งตรงตามกำหนด ไม่เคยผิดหวัง แนะนำสำหรับร้านค้าที่ต้องการสินค้าอุปกรณ์ไฟฟ้าครับ",
        location: "ขอนแก่น",
        date: "2 เดือนที่แล้ว",
        verified: true,
    },
    {
        id: 5,
        name: "คุณสมชาย วงศ์สุวรรณ",
        role: "ช่างไฟฟ้ามืออาชีพ",
        avatar: "สช",
        avatarColor: "from-sky-400 to-blue-500",
        rating: 5,
        text: "ใช้บริการ ElectroMax มา 5 ปีแล้ว สินค้าคุณภาพดีมาก ราคาสมเหตุสมผล และส่งเร็วมาก สั่งวันนี้ได้ของพรุ่งนี้เลย ทีมงานบริการดีเยี่ยม ให้ข้อมูลสินค้าละเอียด แนะนำให้ทุกคนลองใช้บริการเลยครับ",
        location: "กรุงเทพฯ",
        date: "2 สัปดาห์ที่แล้ว",
        verified: true,
    },
];
